### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by cschwartz** [cdlm/infrastructure#1]
Hi,

I'd love to use parts of your script https://github.com/cdlm/infrastructure/blob/master/tools/graffle2pdf in my Rakefile, however I can't find licensing details.

Is there a possibility of adding a license to this repo/specific files?

Best,
  Christian

**Comment by cdlm** [comment]
There you go! If you have that rakefile on github, can you link it in a comment here? It could be useful for people to see both versions.

**Comment by cschwartz** [comment]
Awesome, thank you so much :)
